source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

platform :ios, '8.0'

target 'WWBase_Example' do
      pod 'WWBasicTool', :path => '../'
      pod 'MMKV'        ,'~>1.0.23'
      pod 'WWBaseLib'
end
